name: 🐛 File a bug report
description: X's behavior is deviating from its documented behavior.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information.
  - type: input
    id: Polaris-version
    attributes:
      label: Polaris version
      description: Value of ``polaris.__version__``
      placeholder: 0.2.5, 0.3.0, 0.3.1, etc.
    validations:
      required: true
  - type: input
    id: Python-version
    attributes:
      label: Python Version
      description: Version of Python interpreter
      placeholder: 3.9, 3.10, 3.11, etc.
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: Operating System
      description: Operating System
      placeholder: (Linux/Windows/Mac)
    validations:
      required: true
  - type: input
    id: installation
    attributes:
      label: Installation
      description: How was Polaris installed?
      placeholder: e.g., "using pip into virtual environment", or "using conda"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain why the current behavior is a problem, what the expected output/behaviour is, and why the expected output/behaviour is a better solution.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal, reproducible code sample, a copy-pastable example if possible.
    validations:
      required: true
  - type: textarea
    id: additional-output
    attributes:
      label: Additional output
      description: If you think it might be relevant, please provide the output from ``pip freeze`` or ``conda env export`` depending on which was used to install Polaris.