name: code-check

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"

jobs:

  python-lint-ruff:
    name: Python lint [ruff]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group dev

      - name: Lint
        run: uv run ruff check

      - name: Format
        run: uv run ruff format --check
