name: test

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
      os=${{ matrix.os }}
      - python=${{ matrix.python-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: my_env
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install library
        run: python -m pip install --no-deps -e . # -e (editable is needed for code coverage)

      - name: Run tests
        run: pytest
        env: 
            POLARIS_USERNAME: ${{ secrets.POLARIS_USERNAME }}
            POLARIS_PASSWORD: ${{ secrets.POLARIS_PASSWORD }}

      - name: Test CLI
        run: polaris --help

      - name: Test building the doc
        run: mkdocs build
