name: test

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
      os=${{ matrix.os }}
      - python=${{ matrix.python-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: ./pyproject.toml

      - name: Install the project
        run: uv sync --all-groups --python ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest
        env:
          POLARIS_USERNAME: ${{ secrets.POLARIS_USERNAME }} 
          POLARIS_PASSWORD: ${{ secrets.POLARIS_PASSWORD }}

      - name: Test CLI
        run: uv run polaris --help

      - name: Test building the doc
        run: uv run mkdocs build
